### ISSUE TITLE
front-end layout requirements

### ISSUE THREAD

**Issue by daviortega** [theJensenLab/phyloTreeVizJS#18]
## main layout

* frame centered in the browser window
* tree occupies the entire frame
* frame and tree responsive to changes in the browser window
* font-size of leaf names is responsive

## interacting
* zoom using mouse scroll 
* move tree by click and hold
* collapse of nodes by double click

## tree display layout
* no circles in nodes

**Comment by daviortega** [comment]
relevant to #15

**Comment by tkukavica1** [comment]
for moving the tree, seems like this could be useful to reference:
https://codepen.io/rakeshnayak/pen/MydomJ

**Comment by tkukavica1** [comment]
*centered frame code has been pushed

*now working on dynamic resizing and cursor being able to move the tree

**Comment by daviortega** [comment]
I am closing this since it became three different issues. @tkukavica1 let me know if you disagree or if there is anything here that I am ignoring.
