### ISSUE TITLE
Tree display - vertical

### ISSUE THREAD

**Issue by daviortega** [theJensenLab/phyloTreeVizJS#29]
Probably already done. If so, let's copy here the snippet of code that is responsible for this here and consider it done.

**Comment by tkukavica1** [comment]
function updateVertical()
{
            tree.layout(tnt.tree.layout.vertical().width(window.innerWidth*0.58).scale(false));
            tree.update();
}

**Comment by tkukavica1** [comment]
Overall result is that when Vertical option is selected, controlBar.js calls the code in phylogician.js, which passes the tree into the root function in treelayout.js.

Added the following code to phylogician.js:
```
exports.updateVertical = function() {
	treeLayout.updateVertical(tree)
}
```

Added the following code to new file treelayout.js:
```
exports.updateRadial = function(tree) {
	tree.layout(tntTree.layout.radial().width(Math.min(window.innerWidth * 0.85, window.innerHeight * 0.85))
		.scale(false))
	tree.update()
}
```
