### ISSUE TITLE
Load a tree

### ISSUE THREAD

**Issue by daviortega** [theJensenLab/phyloTreeVizJS#30]
Probably already done. If so, let's copy here the snippet of code that is responsible for this here and consider it done.

**Comment by tkukavica1** [comment]
function submitFile() {
    document.getElementById("errorspot").innerHTML = "";
    var fileInput = document.getElementById("fileInput")
    console.log(fileInput.files[0])
    var newick = ''

    var file = fileInput.files[0]
    var reader = new FileReader()

    reader.onload = function(e) {
        newick = reader.result
        makeTree(newick);
    }
    reader.readAsText(file);
}

**Comment by daviortega** [comment]
All the code is in controlBar.js and some on style.css
Referent to commit 35b23319fc0cbad192d0a2b5edfd83ebc93d3ada
