### ISSUE TITLE
discuss navbar behavior when a new input is added.

### ISSUE THREAD

**Issue by daviortega** [theJensenLab/phyloTreeVizJS#35]
Options:
- retract
- semi-transparent
- nothing

**Comment by daviortega** [comment]
I think we agree that single clicks anywhere will retract/expand navbar. Will work on this now.

and add two more issues:
* opening any input should close the other.
* fix load input file when loading the same file.

**Comment by daviortega** [comment]
fix load input file when loading the same file - ca430bbdef539d27e109e774dc8d3de3577a198b DONE

**Comment by daviortega** [comment]
opening any input should close the other - 8c4dd7a64350c72044394014781f95480d841535 DONE

**Comment by daviortega** [comment]
solved the issue by adding Ctrl+X as a shortcut to expand/retract afe07d9ad6ba8ae4c2191de2d7a4391f47b3d86b

Multiple other little issues were solved in this branch, plus color changes and etc.

**Comment by tkukavica1** [comment]
We discussed this today. It is basically retracting on everything.
