### ISSUE TITLE
## Prep files for dev

### ISSUE THREAD

**Issue by daviortega** [theJensenLab/phyloTreeVizJS#6]
* index.html
* display (((A,B),C),(D,E)) tree

--- Sucess here = printscreen sent by mail and a README explain how to reproduce the code.

**Comment by tkukavica1** [comment]
I have progress + some questions + some confusions. I have tree code that I think is either good or close to working that I accessed online and tailored it to our goal display.

Also I got a new computer so there may be some things missing in the setup that is making things difficult, so we can look at that too (for example I'm having issues committing so for now everything is saved locally).

-Tony

**Comment by daviortega** [comment]
Last commit made it work. Well done
